### ISSUE TITLE
Tworzenie poprawek do projektu / making corrections to project

### ISSUE THREAD

**Issue by Tomirad** [Tomirad/FactorioModsTranslationProject#3]
@Flakopruj 
Różne problemy związane czasem lepiej utworzyć jako ISSUES niż jako komentarze i już karygodne jest dodawanie jakiś X-ów, które można potem przypadkowo dodać.

**Comment by Tomirad** [comment]
Tutaj możesz przedstawić problem z ogonkami.

**Comment by Flakopruj** [comment]
Mam problem z graniem PL. Robię tak:
1. Kopiuję do schowka zawartość spolszczonego pliku. Samego pliku się nie da, bo jego zawartość potem to ...kod strony Githuba, mimo że wyraźnie daję polecenie "Zapisz element docelowy jako", po PPM na nim.
2. Otwieram u siebie katalog z modami: "C:\Users\[Użytkownik]\AppData\Roaming\Factorio\mods".
3. Klikam na zipa moda, otwieram odpowiedni katalog, np. "\angelspetrochem_0.6.1\locale\".
4. Tworzę tam podkatalog /pl, a w nim plik "petrochem.cfg".
5. Wklejam doń zawartość schowka.
6. Gra się nie odpala, jest komunikat: https://zapodaj.net/645ceb574aed7.jpg.html
7. Gdy wgram zawartość schowka do takiego samego pliku, ale w /en, gra działa, ale mam np.:
"Zakład" wyświetla poprawnie, ale:
"Separacja gazów" > "Separacja gaz"
"Tlenek węgla" > "Tlenek w"
"Tworzywo płynne" > "Tworzywo p"
"Żywica" > ""
"Pozostałe Gazy" > "Pozosta"
"Frankcjowanie Ciężkiego Gazu" > "Frankcjowanie Ci" (przy okazji - chyba Frakcjonowanie)
Ewidentny brak plogonków (i dalszego ciągu zdania po tym). Co robię źle? Jak odpalić te mody z plogonkami?

**Comment by Tomirad** [comment]
Sprawdź teraz. Być może kodowanie powinno teraz być poprawne.

Bo co do błędu, zgubiły się 6 zmienny lokalizacji, dodałem je.

**Comment by Tomirad** [comment]
Samo kodowanie powinno być poprawne, bo edycję dokonuje jako UTF-8 without BOM.
W takim kodowaniu zachowane są wszystkie pliku moda.

**Comment by Flakopruj** [comment]
Twoje tłumaczenia są b. fajne - pełne i aktualizowane. Są też inne: (https://mods.factorio.com/mods/sore68/angelsaddons-locales), ale tam wersja PL jest z marca. U Ciebie coś z tym nadal szwankuje, bo np. zamiast "Miał Węglowy" mam "Mia" (ale np. "Paliwo stałe" jest dobrze - kwestia "ł" - obie nazwy w jednym modzie), zamiast "Węgiel" mam "W", zamiast "Żywica" mam "" itd. Może u Ciebie jest dobrze, a do przekłamań dochodzi przy moim kopiowaniu? Kopiuję zawartość pliku do notatnika i taki plik wstawiam do zipa moda (a w notatniku zadeklarowane jest kodowanie "Śródziemnomorskie" - nie z numerkami typu 8859-2).
W "bio-processing.cfg" np. zamiast "Brązowe algi" mam "Br". Ten (i inne pliki angelowe też zmieniałeś, czy tylko "petrochem.cfg"?
Wracając do "locales" - pakiet angelów jest duży. Z kropkami są Twoje prace. Reszty nie ma co zżynać, ale można chyba się tym posiłkować:
* bio-processing.cfg
* ore-refining.cfg
* petrochem.cfg
* smelting.cfg
* warehouses.cfg
* water-treatment.cfg
addon-oldunkle.cfg (nieważny, zaniechany przy 0.14)
addon-pcp.cfg (dodatek innego autora, ale wspiera Angele - PetrochemPlus)
catalysts.cfg
components.cfg
logistic.cfg
names.cfg
pressure-tanks.cfg
ore-silos.cfg

**Comment by Tomirad** [comment]
Zobaczę, ale właśnie widzę, że tam są te tłumaczenia niepełne w stosunku do aktualnej wersji. Ale przejrzę. Sprawdzę jeszcze raz problem z polskimi znakami diakrytycznymi.

W każdym razie inne tłumaczenia też warto dodać do **FactorioModsTranslationProject** aby wszystko było w jednym miejscu.

**Comment by Tomirad** [comment]
Co do kodowania - jeszcze raz, kodowanie powinno być UTF-8 without BOM.
Takie kodowanie mają pliki w /locale/en/*.cfg

**Comment by Flakopruj** [comment]
Co do **"chemical void"** - dostałem w końcu odpowiedź na forum chemicznym, przytoczę najważniejsze:

_Ogólnie wydaje mi się, że problem leży jeszcze gdzie indziej - gra jest produkcji czeskiej, więc sądzę, że ktoś zrobił moda w Czechach lub innym kraju i nieumiejętnie przetłumaczył go na angielski i teraz nawet angol nie będzie wiedział o co chodzi :D
Ja bym to tłumaczył jako "zakład utylizacji odpadów" lub "zakład obróbki odpadów" ewentualnie można dodać na końcu chemicznych, ewentualnie jeżeli jest tam obróbka termiczna to "spalarnia odpadów".
Więc tak naprawdę wszytko zależy co miał na myśli autor moda :)_

Co do plogonków:
W notepad++ jest opcja, by zapisać plik w formacie UTF-8 (bez BOM). Tak z tym plikiem (petrochem.cfg) zrobiłem. Niestety, mam "MiaӠW먬owy" zamiast "Miał Węglowy" itp.
Nie wiem, czy masz dostęp do Factorio. Tam na początku gry nie ma żadnych technologii zaawansowanych (petrochemię trzeba dopiero odkryć). Ale spoko, nie trzeba grać kilkunastu godzin, by zobaczyć efekty. Na factoriowej wiki podają sposób:

1. Kopiujesz do schowka to:
**/c game.player.force.research_all_technologies()**
To robi "Unlock and Research all Technology"
2. Tworzysz nową grę.
3. W tej grze - "tylda" (włącza linię poleceń) i Ctrl+V ze schowka (działa wstawianie, nie trzeba z palca). To trzeba powtórzyć.
4. Oglądasz, czy są plogonki.

Być może to znasz i się niepotrzebnie naklepałem. A może nie - spróbuj. W każdym razie - fajne tłumaczenia, ale co mi po nich, jak nie mogę ich zobaczyć w grze...

**Comment by Tomirad** [comment]
Znam ten kod, stosuje przy pracach developerskich nad Factorio.

Załadowałem moje tłumaczenia do gry i sprawdziłem nazwy:
![image](https://user-images.githubusercontent.com/12190843/33389635-dafe0c78-d533-11e7-9441-6caa83636f17.png)
Są ok.


Ale za to zobaczyłem inne błędy semantyczne:
![image](https://user-images.githubusercontent.com/12190843/33389744-21ed1426-d534-11e7-80a8-7334e8e8efd0.png)

![image](https://user-images.githubusercontent.com/12190843/33389765-3127616c-d534-11e7-9b67-e8ee3df8a7ea.png)


Te elementy w ogóle nie pasują:
![image](https://user-images.githubusercontent.com/12190843/33389862-73e3c6e4-d534-11e7-8198-0f54069633c6.png)

A to w ogóle.
![image](https://user-images.githubusercontent.com/12190843/33389909-95cceec0-d534-11e7-8c28-10da7cce79e3.png)

**Comment by Tomirad** [comment]
Więc nie kopiuj tylko pobierz wszystko i skopiuj do katalogów z modami katalogi modów Angel'sa.
Po pobraniu masz wszakże przygotowane katalogi aby pliki tłumaczeń trafiły prosto do `locale` konkretnego moda.

**Comment by Flakopruj** [comment]
To może głupie, ale nie mogę sobie poradzić z ..."Download this localisation". LPM prowadzi do pliku. Na nim też LPM go otwiera. PPM na katalogu lub potem pliku - jak niżej - chce zapisać całą stronę w html, a nie katalog z zawartością. Pomocy!!! :-)
![fact-pobierzbez tytulu](https://user-images.githubusercontent.com/33991492/33391169-80ac96ae-d538-11e7-89fc-454273caac68.jpg)

**Comment by Flakopruj** [comment]
Usiłuję poprawić coś na początku pliku "petrochem.cfg". Początku nie ma, jest button "expand". A więc rozwijam go, a tam całość zaczyna się od 25 linii. A myślałem o 4:

gas-hydrogen-peroxide=Nadtlenku wodoru
na
gas-hydrogen-peroxide=Nadtlenek wodoru

W ogóle to dziwne, bo to jest w pliku "petrochem.cfg", a na screenie tej modyfikacji nie ma. "Bob metals" też nie. Sprawdziłem też "boblocale" i też nie ma choćby częściowego zwrotu "nadtl".
W przypadku "Napełnij beczkę czegośtam" to pasuje, ale "angelsrefining.cfg" (widoczny na screenie) też tego nie ma. Zwrot "Napełnij..." ma "ł", tytuł modyfikacji, żeby mi działał mod (po staremu i to też nie jest "angelsrefining.cfg") to "Obsluga plynow". W sumie nie wiem, czy to jest do poprawy, czy dobrze, nie mogę tego namierzyć.

![obraz](https://user-images.githubusercontent.com/33991492/33400282-d5885952-d555-11e7-9268-fb9d563c469c.png)

**Comment by Tomirad** [comment]
Kolego, źle pobierasz, tak się nie pobiera danych z Githuba :D

Po korzystamy z Githuba, żeby móc współpracować z innymi osobami, które mogą edytować kod bezpośrednio na Githubie a potem można łączyć kod który coś ulepsza lub poprawia. - tak zrobiłem z jedną z twoich edycji.

![image](https://user-images.githubusercontent.com/12190843/33415607-d5e444a0-d597-11e7-9aa8-8a94a7481094.png)

Druga możliwość jeżeli twórca wydał wersję to https://github.com/Tomirad/FactorioModsTranslationProject/releases
Ja wydałem pro-forma. W moim przypadku nie jest to potrzebne.

**Comment by Tomirad** [comment]
Ja znalazłem: był w petrochem.cfg
Poprawiłem.

**Comment by Flakopruj** [comment]
I życie stało się piękne! Po Twoim wyjaśnieniu o kopiowaniu, wszystko śmiga. Dzięki.

**Comment by Flakopruj** [comment]
Nie wiem gdzie to (może raz z Angelów, a raz z Bobów, może to nie problem): w Helmodzie tak mam - raz iron, raz żelazo.
![ruda_zel](https://user-images.githubusercontent.com/33991492/33517825-4095470a-d78b-11e7-8dab-964d3054140d.jpg)

**Comment by Flakopruj** [comment]
Te zmiany są pod "Expand", ale tam nie mogę edytować; z pewnością ta funkcja jest do czegoś potrzebna, jak dotąd tylko irytuje.

Zbiorczo:

petrochem.cfg
-------------
106 mineral-oil-lubricant=Lubrykant > Smar ?
Tłumaczenie słuszne, ale w polskim "Lubrykant" kojarzy się raczej z sypialnią :-)

209  angels-flare-stack=Pochodnia Gazowa
285 chemical-void=Utylizator Chemiczny
333  [item-description] angels-flare-stack=Spalarnia chemikaliów (Chemical void)
382  [entity-description] angels-flare-stack=Spala nadmiar substancji chemicznych (Utylizacja)
Tak ma być?

241  angels-electric-boiler=Kocioł Elektryczny
270  angels-electric-boiler=Kocioł elektryczny
Duża/mała litera

348 basic-chemistry=Basic Chemistry > Podstawowa chemia
358 angels-advanced-chemistry=Zaawansowana Chemia
Nie chodzi o różnicę między podstawową a zaawansowaną, ale o spolszczenie nazwy.

ore-refining.cfg
----------------
352 loc-upf=Fluoryt
354 loc-fluorite=Fluoryt
upf to to samo, co niżej?

357 burner-ore-crusher=Nie wsadzaj swoich paluszków bo inaczej je stracisz
I dalsze trzy > przed "bo" przecinek

366  ore-leaching-plant=Dalsza obróbka rudy za pomocą ługowania chemicznego
a w "petrochem.cfg" 397 angels-enable-acids=Zmienia receptury Ługowania...
Chodzi o "ługowanie" - duża/mała litera.

**Comment by Tomirad** [comment]
Lubrykant - to poprawna nazwa z perspektywy technicznej, poprawiłem na Smar Mineralny, aby odróżnić od Smaru który jest w bazowej wersji gry.

Reszta... np. z Podstawową chemią, to przeoczenie :)

Fluoryt - chyba tak, można sprawdzić na wersji podstawowej.

Ługowanie - z dużej bo odnoszę się do nazwy receptury, w 366 to nazwa czynności.

**Comment by Flakopruj** [comment]
Co do przeoczeń - nie trzeba się tłumaczyć, zdarza się i fajnie, jak je można wyłapać, po to m.in. tu jestem :-)

**Comment by Tomirad** [comment]
Wiem, wiem... dlatego nie każdą uwagę komentuję :)
